### DISCUSSION TITLE
Can SWA CLI tear down infra?

### DISCUSSION THREAD

**Discussion by johnkors** [Azure/static-web-apps-cli#547] [Q&A]
Hi,

If I understand the GitHub action correctly, it will tear down/remove the static web app if the PR is closed. 

```yml
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
```

Is there a similar function to "close" for SWA CLI?
