### ISSUE TITLE
Github actions deploying only to production instead of preview environments

### ISSUE THREAD

**Issue by andrewreeman** [Azure/static-web-apps-cli#661]
**Describe the bug**
I have noticed the last few github action builds have been deployed to the production website instead of the preview environment.
The workflow file hasn't changed and the branch is not the main branch.
This seems to have happened since the docker image at mcr.microsoft.com/appsvc/staticappsclient:stable was updated.
The last successful run was when github actions was using the docker image with a sha digest of: 
6e8c2f7004cfd75ccbf2d1f5a402999432989eecd692d5536d47d46a07bb22ff

This issue started happening since the stable docker image was updated with a sha digest of:
870e5b73cf8d832615253d71b5834563b581a3fdf1a3defc26ccdfa264b37235

**Github actions**
```
- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_044CD3B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"                    
          app_location: "/"
          api_location: "api/api"
          output_location: "dist"
          production_branch: "main"
```

**Screenshots**
This is what used to happen:
<img width="687" alt="swa-good" src="https://user-images.githubusercontent.com/1423405/221717769-6f81820d-4749-49ad-a0d0-3ffb39f95b91.png">

And now it's not going to a develop preview environment:
<img width="526" alt="swa-bad" src="https://user-images.githubusercontent.com/1423405/221717799-4f7c03c9-c869-479a-bcee-477a00af25f4.png">

Hopefully this issue can be fixed. Happy to provide more details if needed.
Really enjoying Static Web Apps by the way. Great work!
