### ISSUE TITLE
Getting zero exit code on deploy failure

### ISSUE THREAD

**Issue by pstovik** [Azure/static-web-apps-cli#665]
**Describe the bug**
There is an upload failure, but CLI returns 0 exit code.

**To Reproduce**

1. Given issue with SWA Azure - like this one => https://github.com/Azure/static-web-apps/issues/1097
2. When running the command 'swa deploy --env production'
3. Then I can see error in log 
>✖ Deployment Failed :(
>✖ Deployment Failure Reason: Failed to deploy the Azure Functions.
 and exit code is "0"

**Expected behavior**
Have non-zero exit code, to get failures in pipelines

**Screenshots**
![2023-03-08 non-zero](https://user-images.githubusercontent.com/19603788/223728885-5dfe4521-10db-4ecb-b46f-20a0e5632c07.png)

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 11 (bullseye)
- Version 1.0,6

**Comment by flexwie** [comment]
We are getting the same behaviour when trying to deploy a new env without any free slots available.
Our workaround for pipelines is a shell script that greps the output for a keyword:

```sh
swa deploy -O build/your-app --env "full_env"  2>&1 | tee run.log
if grep -q BadRequest run.log; then exit 1; else exit 0; fi
```

**Comment by dylan-smith** [comment]
the always 0 exit code makes it really hard to use this in any CI/CD scenario. I want to fail my GitHub Actions workflow if deploy fails, but since the `swa` exit code is is 0, GitHub Actions assumes it succeeded (as will most/all CI systems).

**Comment by hbroer** [comment]
yea it is anoying. We run into this from first try because 1st we thought "nice that was easy" but then "oh no, it errors bur it does not fail". 

It needs to return an error code, else we need to look into the job everytime.

**Comment by atharva407** [comment]
Surprised to see that this issue still exists? Any updates or a better workaround for this to be used in CI/CD Systems?

**Comment by hbroer** [comment]
Hey, I forgot it twice, sorry guys :-D

This is our quick and dirty solution from our CI/CD config (Gitlab), which runs like this since a while:
```yml
  before_script:
    - npm install -g @azure/static-web-apps-cli@1.1.4
  script:
    - cp -r ./static/* ./$DISTDIR
    - swa deploy --deployment-token $DEPLOYMENT_TOKEN --env=production ./$DISTDIR |& tee deploy.log
    - cat deploy.log | grep -q "Project deployed to"
    # swa does not return a status code other than 0. so we search in ihe output for a "success" string.
```

@adematte changing it would not be a problem with a 2.x No flag needed. IMO the current behavior is just wrong and a bug.
